### PR TITLE
Remove docker images once the integration test completes.

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
Failing due to the last command failing. Maybe ignore it's return?

**Comment by vishh** [comment]
Yeah. That makes sense. Done.

**Comment by vmarmol** [comment]
LGTM, will merge on green.

**Comment by vishh** [comment]
@vmarmol: Tests are passing!

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
