### PR TITLE
Add kubernetes master authentication args & config to kube source

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by vishh** [comment]
ok to test.

**Comment by vishh** [comment]
@jimmidyson: Will auth be necessary even if heapster were to use the readonly master service `kubernetes-ro`?

**Comment by jimmidyson** [comment]
@vishh - it depends on the implementation. I know at least one that requires authentication for both `kubernetes` & `kubernetes-ro`. Even the RO service can expose info... We at least need the capability to auth, regardless.

**Comment by jimmidyson** [comment]
@vishh - btw this failed earlier because of the github outage :( it's not building again for some reason.

**Comment by vishh** [comment]
@jimmidyson: Suggestion. Can we use the [kube clientauth](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/clientauth/clientauth.go) library instead? @erictune is working on introducing secrets into containers and using the clientauth library will be necessary soon.

**Comment by jimmidyson** [comment]
@vishh - yes this makes a lot more sense. I was unaware of this coming but I like it :) Are there any timescales for when this will be supported in a kubernetes release?

**Comment by vishh** [comment]
@etune mentioned that he was going to start working on it today. So I
expect to see something in a week on Kubernetes HEAD.

**Comment by jimmidyson** [comment]
@vishh - ok i'll update this PR to use `clientauth` & we can wait to merge it until it's usable in Kubernetes?

**Comment by vishh** [comment]
SGTM

**Comment by jimmidyson** [comment]
@vishh - i guess we could merge this now as it defaults to disabled & only use when introducing secrets to containers is sorted in kubernetes?

**Comment by vishh** [comment]
LGTM. 
@jimmidyson: Agreed. Merging this PR now. Thanks for the PR!

**Pull request merged**
