### PR TITLE
Add firewall rules for integration testing.

### PR DESCRIPTION
**Pull request by vishh**
also fixed bugs in integration test.

### CODE REVIEW

**Comment by rjnagal** [comment]
This time it timed out ... took 10m. I think its close to be fixable.

**Comment by vishh** [comment]
I have restarted the build with an increased timeout.

**Comment by rjnagal** [comment]
I think its getting stuck somewhere. Timed out again after 15mins.

**Comment by vishh** [comment]
Increased the timeout once again and restarted the build. I hope jenkins will update github upon success.

**Comment by vishh** [comment]
@rjnagal: Jenkins is green now :)

**Comment by rjnagal** [comment]
LGTM, finally :)

**Pull request merged**
