### PR TITLE
Releasing heapster v0.14.1

### PR DESCRIPTION
**Pull request by vishh**
Depends on #346 

The images have not been built and pushed. Kindly LGTM and wait for the images to be pushed before merging this PR.

### CODE REVIEW

**Comment by vishh** [comment]
cc @rjnagal

**Comment by rjnagal** [comment]
LGTM,

will merge after deps are in.

**Comment by rjnagal** [comment]
Need to trigger tests again.

**Comment by vishh** [comment]
@rjnagal: Tested manually. PTAL

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
