### PR TITLE
Update resolution to be 30 seconds and poll duration to be a minute.

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vishh** [comment]
cc @vmarmol

**Comment by vmarmol** [comment]
LGTM, thanks @vishh :) this will help as we scale.

**Comment by vmarmol** [comment]
Jenkins failing :(

**Comment by vishh** [comment]
@vmarmol: Instead of this PR, how about updating GCM kube-config to downsample more?

**Comment by vishh** [comment]
Closing this PR. Happy to re-open if a config based strategy will not work.

**Pull request closed without merging**
