### PR TITLE
Updating to use v1beta3 API of Kubernetes

### PR DESCRIPTION
**Pull request by krousey**

### CODE REVIEW

**Comment by vishh** [comment]
@cadvisorJenkinsBot: ok to test

**Comment by krousey** [comment]
If everything passes, how long would it take to push a new container image so I can update the Pod specs in Kubernetes?

**Comment by vishh** [comment]
@krousey: I can make a new release tomorrow.

**Comment by krousey** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
Thanks

**Comment by krousey** [comment]
I updated the change to reflect minions being replace by nodes and DesiredState being replaced by spec.

**Comment by vishh** [comment]
Thanks for the fix @krousey. LGTM

**Pull request merged**
