### PR TITLE
Fix exit code issue in jenkins integration test script.

### PR DESCRIPTION
**Pull request by vishh**
Its time to do all this in golang and not get bitten by bash in the future.

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
Will wait for green.

**Comment by vishh** [comment]
Sadly the fix was wrong :(. The test failed in reality!

**Comment by vmarmol** [comment]
:( why did Jenkins report green?

**Comment by vishh** [comment]
That is what I am trying to fix through this PR. It is incorrectly
reporting green. Nvm. It is still broken. Nothing has changed.

**Pull request merged**
