### PR TITLE
Refactoring sinks API in-order to reliably expose the metrics schema via REST API

### PR DESCRIPTION
**Pull request by vishh**
This PR includes a rest endpoint 'api/v1/metrics-export-schema' that contains the schema for all metrics exposed by heapster.
The integration test has been updated to use the schema to validate all the metrics returned by heapster.

### CODE REVIEW

**Comment by vishh** [comment]
cc @rjnagal: This the test change I was referring to offline, that will prevent API issues in the future.

**Comment by vishh** [comment]
@rjnagal: PTAL. Rebased to HEAD!

**Comment by rjnagal** [comment]
Can you describe all the pieces in this PR a bit more for my reference.

**Comment by vishh** [comment]
1. Refactor sinks internal API to have a static schema and versioning.
2. Expose the metrics API schema.
3. Modify the integration test to validate the API output against the
schema.

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
