### PR TITLE
- Fix Pod with Namespace

### PR DESCRIPTION
**Pull request by cedbossneo**

### CODE REVIEW

**Comment by cedbossneo** [comment]
Split of the pullrequest #105

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
LGTM, will merge when the CI passes. Thanks for the patch @cedbossneo!

**Comment by vmarmol** [comment]
Looks like Jenkins is failing

**Comment by vmarmol** [comment]
```
+ godep go test -a -v '--vmodule=*=1' --timeout=30m --namespace=default --kube_versions=0.10.0 github.com/GoogleCloudPlatform/heapster/integration/...
=== RUN TestHeapsterInfluxDBWorks
I0217 15:02:11.331626   25980 framework.go:248] Disabled cluster monitoring
I0217 15:02:11.332002   25980 framework.go:251] Setting up new kubernetes cluster version: 0.10.0
I0217 15:02:11.332060   25980 framework.go:142] Bringing down any existing kube cluster
I0217 15:08:20.974312   25980 framework.go:270] Successfully setup new kubernetes cluster version 0.10.0
I0217 15:08:24.448101   25980 framework.go:192] Kubernetes master IP is 130.211.153.5
I0217 15:08:24.620576   25980 framework.go:369] Cannot find Replication Controller "monitoring-heapster-controller". Skipping deletion - replicationController "monitoring-heapster-controller" not found
I0217 15:08:24.625657   25980 framework.go:369] Cannot find Replication Controller "monitoring-influx-grafana-controller". Skipping deletion - replicationController "monitoring-influx-grafana-controller" not found
I0217 15:08:24.630485   25980 framework.go:354] cannot find service "monitoring-influxdb" - service "monitoring-influxdb" not found
I0217 15:08:24.774790   25980 kube_test.go:166] waiting for pods to be running
I0217 15:09:09.901397   25980 kube_test.go:84] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
--- FAIL: TestHeapsterInfluxDBWorks (418.57 seconds)
	assertions.go:154: 
                        
	Location:	kube_test.go:205
		
	Error:		No error is expected but got 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
		
FAIL
exit status 1
FAIL	github.com/GoogleCloudPlatform/heapster/integration	418.578s
```

**Comment by vishh** [comment]
LGTM. Jenkins failure looks like etcd issue. I have restarted the build. Will merge once the build passes.

**Comment by vmarmol** [comment]
Sadly I think it is more subtle than that from my restart of the build before. But maybe it likes you more so we'll see :)

**Comment by vishh** [comment]
A subsequent run of CI passed. But jenkins failed to update github - http://104.154.52.74/job/heapster-e2e-gce/398/

Merging this PR.

**Comment by vmarmol** [comment]
Oh wow Jenkins fine, work for @vishh and not for me. I don't know what to think of this betrayal Jenkins.

**Pull request merged**
