### PR TITLE
Make heapster use monitoring secret to connect with kubernetes master securely

### LINKED ISSUE #269: Update heapster to use kubeconfig credentials on kubernetes
In the file where you currently create a client using kubernetes_auth file, do something like this:

```go
import (	kclientcmd "github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd" )
...

kubecfg_file          = flag.String("kubecfg_file", "", "Location of kubecfg file for access to kubernetes service")
...

func newKubeClient() (*client.Client, error) {
  var config *client.Config
  if *kubecfg_file != "" {
    var err error
    if config, err = kclientcmd.NewNonInteractiveDeferredLoadingClientConfig(
      &kclientcmd.ClientConfigLoadingRules{ExplicitPath: *kubecfg_file},
      &kclientcmd.ConfigOverrides{}).ClientConfig(); err != nil {
        return nil, err
    }
  } else {
    // however you handle this case
  }
  return client.New(config), nil
}
```

And in your pod template add:
```yaml
volumeMounts:
- name: monitoring-token
  mountPath: /etc/kubernetes/kubeconfig
  readOnly: true
```

and in the heapster container of the pod template add:
```yaml
volumes:
 - name: dns-token
   source:
    secret:
     target:
       kind: Secret
       namespace: default
       name: token-system-monitoring
```

And add this argument to heapster `--kubeconfig=/etc/kubernetes/kubeconfig`

### PR DESCRIPTION
**Pull request by vishh**
Fixes #269

### CODE REVIEW

**Comment by vishh** [comment]
Ping @vmarmol

**Comment by vmarmol** [comment]
LGTM

**Comment by lgfausak** [comment]
i've been trying to deploy heapster on my coreos/kubernetes cluster. i can't get heapster to start using the deploy/influxdb resource files. I figured out i need to add a token-system-monitoring secret, but, i don't know what the format of that secret is.  without the secret the heapster pod hangs with a 'Waiting' status, it is waiting on the mount resource.  I added a blank one with:

    {
      "apiVersion": "v1beta2",
      "kind": "Secret",
      "id": "token-system-monitoring",
      "data": {
      }
    }

Although this got me past the hanging, now the heapster just restarts constantly, 

    2015-05-13T15:32:32.663447125Z + /usr/bin/heapster --sink influxdb:http://10.100.95.142:80 --source=kubernetes:http://10.100.0.1:80
    2015-05-13T15:32:32.663454073Z I0513 15:32:32.662521       7 heapster.go:52] /usr/bin/heapster --sink influxdb:http://10.100.95.142:80 --source=kubernetes:http://10.100.0.1:80
    2015-05-13T15:32:32.663459690Z I0513 15:32:32.662590       7 heapster.go:53] Heapster version 0.12.0
    2015-05-13T15:32:32.663466175Z E0513 15:32:32.662661       7 heapster.go:59] The config file /etc/kubernetes/kubeconfig/kubeconfig does not exist

the mount path is declared here:

                        "volumeMounts": [
                            {
                                "name": "ssl-certs",
                                "mountPath": "/etc/ssl/certs",
                                "readOnly": true
                            },
                            {
                                "name": "monitoring-token",
                                "mountPath": "/etc/kubernetes/kubeconfig",
                                "readOnly": true
                            }
                        ]

so i am guessing that i have the configuration incorrect for the secret definition.  where can i look to see how that should be defined?  I posted a question about this on google containers as well.  I have been trying to get heapster started on and off for a couple of weeks now :-)

**Comment by vishh** [comment]
@lgfausak: Tokens are required for access to the kube api-server. Kubernetes exposes two default services to access the apiserver - one requires no auth and is read-only (`kubernetes-ro`); the other requires auth (`kubernetes`) and is read-write. Kubernetes is in the process of dropping support for `kubernetes-ro` service. Heapster used to use the `kubernetes-ro` service until recently.
For the short-term, until you figure out how to setup tokens for cluster services, I am making a change to heapster to make it possible to run heapster using `kubernetes-ro` service. I will get back to you with specific instructions once the required changes are in.

**Comment by lgfausak** [comment]
standing by, thank you.

On Wed, May 13, 2015 at 2:34 PM, Vish Kannan <notifications@github.com>
wrote:

> @lgfausak <https://github.com/lgfausak>: Tokens are required for access
> to the kube api-server. Kubernetes exposes two default services to access
> the apiserver - one requires no auth and is read-only (kubernetes-ro);
> the other requires auth (kubernetes) and is read-write. Kubernetes is in
> the process of dropping support for kubernetes-ro service. Heapster used
> to use the kubernetes-ro service until recently.
> For the short-term, until you figure out how to setup tokens for cluster
> services, I am making a change to heapster to make it possible to run
> heapster using kubernetes-ro service. I will get back to you with
> specific instructions once the required changes are in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/heapster/pull/279#issuecomment-101787478>
> .
>



-- 
Greg Fausak
lgfausak@gmail.com

**Pull request merged**
