### PR TITLE
Fixing coreos docs for proper operation.

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Couldn't get heapster to properly work on coreos until I made the following changes.

### CODE REVIEW

**Comment by hyperbolic2346** [comment]
I signed it!

**Comment by vishh** [comment]
@hyperbolic2346: Thanks for the PR! The coreos documentation does require some updates. I have opened #305 to fix the docs. Can you check if the steps in #305 work for you?

**Comment by hyperbolic2346** [comment]
Added fleet files with updated versions from @vishh .

**Comment by vishh** [comment]
@cadvisorJenkinsBot: ok to test.

**Comment by vishh** [comment]
@hyperbolic2346: LGTM. Needs a rebase though.

**Comment by vishh** [comment]
LGTM

**Pull request merged**
