### PR TITLE
Add support to run heapster using Kube v1beta3 API.

### LINKED ISSUE #206: Heapster deployed in v1beta3 hits cluster with v1beta1
From IRC:

```
4:24 AM <Gui_> i deployed heapster with api v1beta3... but heapster container try to join k8s api with v1beta1 ???
4:26 AM <Gui_> why create v1beta 3 deploy scripts if heapster try to reach the master with v1beta1
4:31 AM <jdyson> Gui_, agreed it's not very consistent, does it affect functionaity?
4:32 AM <Gui_> yes it doesn't work
4:32 AM <Gui_> heapster try to contact api server, certainly to retrieve metrics
4:32 AM <Gui_> and 404 error
4:33 AM <Gui_> I deploy a new cluster in v1beta1 api
4:33 AM <Gui_> to try heapster
4:34 AM <Gui_> I didn't find a way to work with heapster with the previous version
4:35 AM <Gui_> i hope i can be today
4:36 AM <Gui_> always dependancy pb between k8s versions
```

### PR DESCRIPTION
**Pull request by vishh**
Fixes #206

### CODE REVIEW

**Comment by rjnagal** [comment]
sources/kube.go:242: undefined: kubeClientVersion
sources/kube.go:260: undefined: kubeClientVersion

**Comment by vishh** [comment]
@rjnagal: Sorry, I was too hasty. Fixed the issues.

**Comment by rjnagal** [comment]
LGTM. Waiting for tests.

**Comment by rjnagal** [comment]
The test failed :(

**Comment by vishh** [comment]
Ping @rjnagal. This is ready to be merged.

**Pull request merged**
