### PR TITLE
Feature updates to heapster

### PR DESCRIPTION
**Pull request by vishh**
1. Removed elasticsearch dependency - faster pulls and start up time for grafana
2. Placed all components behind a replication controller
3. Added a Grafana service in preparation for getting rid of host ports.
4. Updated dependencies to static versions instead of 'latest'.

Note: The changes to Godeps will disappear once #37 has been merged.

### CODE REVIEW

**Comment by vishh** [comment]
cc @rjnagal @vmarmol. If possible try running heapster with this PR.

**Comment by rjnagal** [comment]
I am going to try this patch tonight.

**Comment by rjnagal** [comment]
Can you rebase to remove Godeps and squash other patches? It'll make it easier to cherrypick.

**Comment by vishh** [comment]
@rjnagal: Rebased and squashed a few commits.

**Comment by vmarmol** [comment]
Changes LGTM, will try out in a cluster now.

**Comment by vmarmol** [comment]
Finally got around to testing this. I works as expected. The only change would be to update the README with the new instructions :)

Feel free to do that in another PR. Merge away!

**Comment by vishh** [comment]
Thanks for the update @vmarmol.

**Pull request merged**
