### PR TITLE
Added aligning stats timestamps to multiple of resolution

### PR DESCRIPTION
**Pull request by piosz**
This is required to add a possibility of aggregating stats for node/cluster
needed for autoscaling purposes.

### CODE REVIEW

**Comment by piosz** [comment]
@vmarmol, @vishh are you ok with such change? If yes I'll add unit test.

**Comment by vmarmol** [comment]
@afein you were working on something similar no?

**Comment by afein** [comment]
Hey @piosz, indeed I am working on something very similar which involves both stat alignment and aggregation. 

Feel free to take a look at how aggregation and alignment is implemented in #388 and let us know if that satisfies your use cases. After that PR is merged, the next PR involves REST endpoints for all metrics.

Here are some example REST endpoints:

/api/v1/model/cluster/cpu-usage
/api/v1/model/pod/monitoring-heapster-xk12d/memory-usage
/api/v1/model/namespace/default/cpu-limit

The JSON response for these endpoints would be a single timeseries, represented as a list of timestamp-value pairs. These endpoints also have an optional starting time parameter, so you can only get metrics that are newer than your specified time.

You can take a look at the core of the next PR here:
https://github.com/GoogleCloudPlatform/heapster/compare/master...afein:schema7

Let me know if that model would work in your use case, in which case we can speed up the merge process to let you access that functionality faster!

**Comment by piosz** [comment]
@afein maybe you can review this PR?

**Comment by afein** [comment]
LGTM, but @vmarmol should review it as well

**Comment by vmarmol** [comment]
LGTM

**Comment by piosz** [comment]
Thanks!

**Pull request merged**
