### PR TITLE
Add major page fault metric

### PR DESCRIPTION
**Pull request by vmarmol**
/cc @vishh

### CODE REVIEW

**Comment by vishh** [comment]
Wonder why the integration test is failing.

**Comment by vmarmol** [comment]
Passed, although I forgot to update the storage schema, will do that now.

**Comment by vmarmol** [comment]
Pushed the new commit with the doc updates.

**Comment by vishh** [comment]
I don't see the docs @vmarmol

**Comment by vmarmol** [comment]
Ooops my bad, should be updated now @vishh

**Comment by vishh** [comment]
LGTM

**Pull request merged**
