### PR TITLE
Fixed a bug in external sink manager 

### PR DESCRIPTION
**Pull request by vishh**
It was pushing data to only one sink.
Made external sinks push data in parallel.
Improved debuggability.

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
Jenkins is failing btw

**Comment by vishh** [comment]
Manual testing seems to work. I have made some more refactoring and updated the code.

**Comment by vmarmol** [comment]
Jenkins still fails reliably :( is this something we should worry about?

**Comment by vishh** [comment]
Most likely yes. I will look into the failing cluster some time soon.

**Comment by vishh** [comment]
@vmarmol: Jenkins is green. I didn't change anything since the last failing run.

**Pull request merged**
