### PR TITLE
Update integration tests to work with the new build model that uses makefile

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by vishh** [comment]
@cadvisorJenkinsBot: test this please

**Comment by jimmidyson** [comment]
@vishh - fancy updating travis.yml at the same time? Then we're at least conistent.

**Comment by vishh** [comment]
@jimmidyson: Good idea. Done.

**Comment by vishh** [comment]
@vmarmol: I made some more changes to the makefile and travis config. PTAL

**Comment by vmarmol** [comment]
LGTM

**Pull request merged**
