### PR TITLE
Let Heapster monitor localhost with an empty hosts file.

### PR DESCRIPTION
**Pull request by vmarmol**

### CODE REVIEW

**Comment by rjnagal** [comment]
Would it be a problem if we accidentally forgot to add the flag and heapster just continued assuming localhost?

**Comment by vmarmol** [comment]
The default of the flag is a specific file, so you'd have to specifically set it to the empty string.

**Comment by rjnagal** [comment]
I just realized that after sending the comment.

LGTM

**Comment by vmarmol** [comment]
:)

**Comment by vishh** [comment]
LGTM

**Pull request merged**
