### PR TITLE
Update integration tests to use kube version v0.14.1 [Attempt 2].

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
@vishh is that build live? It's having trouble pulling it. Maybe lets use 0.14.0 for now?

**Comment by vishh** [comment]
0.14.0 has a bug. Wasted a lot of time on that. 0.14.1 shoudl be fine. Zach
is fixing the release so that a tarball will be available.

**Comment by vmarmol** [comment]
Green :D

**Pull request merged**
