### PR TITLE
Grafana v0.4 with proxy service support

### PR DESCRIPTION
**Pull request by vishh**
Depends on #78

### CODE REVIEW

**Comment by vishh** [comment]
@rjnagal, @vmarmol: Kindly test this PR if possible before merging.
You can use `deploy/kube.sh restart` command to test this PR.

**Comment by vmarmol** [comment]
Does this need to be rebased with the PR you sent a couple of days ago?

**Comment by vmarmol** [comment]
I guess not since you built the images :)

**Comment by vishh** [comment]
I have already rebased. Sorry failed to update the PR. Can you test it once
before merging?

**Comment by vishh** [comment]
I need to fix the integration test to access influxdb via the proxy on api-server.

**Comment by vishh** [comment]
This PR is ready to be merged as well. The integration test has been updated to work without firewall rules.

**Comment by vmarmol** [comment]
LGTM

**Pull request merged**
