### PR TITLE
Bug fixit and minor file reorganization.

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by rjnagal** [comment]
Test failure in vmodule revert, haha. Suitable punishment for bundling all patches together :)

**Comment by vishh** [comment]
@rjnagal: I accumulated all these patches while trying to make a new heapster release. The test failure is due to file re-org. Updated the test now.

**Comment by rjnagal** [comment]
Still failing integration:
I0313 17:53:28.043127    6702 framework.go:393] Cannot find Replication Controller "monitoring-heapster-controller". Skipping deletion - replicationController "monitoring-heapster-controller" not found
I0313 17:53:28.045736    6702 framework.go:393] Cannot find Replication Controller "monitoring-influx-grafana-controller". Skipping deletion - replicationController "monitoring-influx-grafana-controller" not found
I0313 17:53:28.049257    6702 framework.go:378] cannot find service "monitoring-influxdb" - service "monitoring-influxdb" not found
I0313 17:53:41.043606    6702 kube_test.go:252] waiting for pods to be running
--- FAIL: TestHeapsterInfluxDBWorks (260.81 seconds)
	assertions.go:154: 
                        
	Location:	kube_test.go:311
		
	Error:		No error is expected but got pod not in running state after 60 seconds
		
FAIL
exit status 1
FAIL	github.com/GoogleCloudPlatform/heapster/integration	260.821s
godep: go exit status 1

**Comment by vishh** [comment]
@rjnagal: Fixed the integration tests. This PR is ready for review.

**Comment by rjnagal** [comment]
LGTM.

waiting on integration tests.

**Pull request merged**
