### PR TITLE
Added comments, replaced string literals with constants

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
Addressed @vmarmol comments from  #384

**Comment by vmarmol** [comment]
ok to test

**Comment by vmarmol** [comment]
Thanks @piosz! Looks like we're missing gofmt on some files:

```
Run gofmt on the following files:
 ./sinks/gcmautoscaling/driver.go
```

**Comment by vmarmol** [comment]
LGTM

**Comment by piosz** [comment]
Fixed. Sorry for missing this.

**Comment by vmarmol** [comment]
np :) will merge on green.

**Pull request merged**
