### PR TITLE
Move heapster to a vanity import

### PR DESCRIPTION
**Pull request by mikedanese**
GoogleCloudPlatform/kubernetes#12211

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
Thanks for the update @mikedanese

**Comment by mvdan** [comment]
LGTM, thanks @mikedanese for fixing travis/jenkins. Could you squash?

**Comment by mikedanese** [comment]
I've separated automated import rewrite from manual build fix into separate commits intentionally. This is recommended by the guideline [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#when-to-retain-commits-and-when-to-squash). I think it makes sense not to squash.

**Comment by mvdan** [comment]
Fair enough.

Jenkins is acting up again... retest this please

**Comment by mikedanese** [comment]
All green again.

**Comment by mvdan** [comment]
Thanks @mikedanese!

**Comment by mikedanese** [comment]
P.S., this will require people to update their gopath layout.

```
mkdir -p $GOPATH/src/k8s.io
mv $GOPATH/src/github.com/GoogleCloudPlatform/heapster $GOPATH/src/k8s.io
```

**Comment by mvdan** [comment]
Many people will run into this issue, so I'm thinking we better have it in the README for a couple of weeks. Thoughts?

**Comment by mvdan** [comment]
Just as well, the README should specify that people should use `k8s.io/*` for `go get` et al instead of the full `github.com/GoogleCloudPlatform/*` url.

**Comment by mikedanese** [comment]
Yes, I can add that. I've also sent out an announcement on kubernetes-dev, google-containers and kubernetes-announce.

https://groups.google.com/forum/#!topic/kubernetes-announce/d5Yq_y4hbac

**Pull request merged**
