### PR TITLE
Have git ignore VIM scratch files

### PR DESCRIPTION
**Pull request by saad-ali**
CC @vishh

### CODE REVIEW

**Comment by rjnagal** [comment]
Probably easier to put it in your global git preferences.

**Comment by saad-ali** [comment]
Good point. Wouldn't hurt to have it as part of the project though (Kubernetes does).

**Comment by rjnagal** [comment]
I don't mind it, I just gave up trying to update repos some time ago :)

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
