### PR TITLE
update k8s dep

### PR DESCRIPTION
**Pull request by lavalamp**
Let's see if this pleases the godep gods.

### CODE REVIEW

**Comment by vmarmol** [comment]
ok to test

**Comment by lavalamp** [comment]
OK, I think I may have figured it out, let's see...

**Comment by lavalamp** [comment]
OK, this time I updated only the bare minimum. Let's see if this one works. (it passes tests this time...)

**Comment by lavalamp** [comment]
Looks like this one is going to pass. Although jenkins can't run the boilerplate checker for some reason?

**Comment by vmarmol** [comment]
LGTM, thanks @lavalamp!

**Comment by lavalamp** [comment]
hm, integration test failed... @vmarmol do you know why?

**Comment by lavalamp** [comment]
I'll run integration locally and see if that works?

**Comment by lavalamp** [comment]
I think the integration test is broken because we moved addons into the kube-system namespace.

**Comment by lavalamp** [comment]
Running again with kube-system namespace.

**Comment by lavalamp** [comment]
Fixing a bug in the integration test...

**Comment by mvdan** [comment]
I just fixed integration tests in #431, so let's run them again.

**Comment by mvdan** [comment]
retest this please

**Comment by mvdan** [comment]
retest this please

**Comment by vishh** [comment]
@cadvisorJenkinsBot: retest this please

**Comment by vishh** [comment]
retest this please

**Comment by mvdan** [comment]
The last jenkins job succeeded. Should we merge?

**Comment by vishh** [comment]
Yes.

**Pull request merged**
