### PR TITLE
Reenable sinks gcm integration test

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
Okay, the gcm sink integration test is still failing with the cert issue. @vishh, you mentioned a PR that should fix this, which was it?

**Comment by vishh** [comment]
#445

**Comment by mvdan** [comment]
@vishh I'm guessing those changes need to be done on the other configs - especially the `standalone` one - for them to matter here.

**Comment by mvdan** [comment]
Reping @vishh

**Comment by vishh** [comment]
@mvdan: That's correct. Can you update this PR by cloning #445 into the standalone config as well?

**Comment by mvdan** [comment]
@vishh looks like it failed all the same.

**Comment by vishh** [comment]
Did you try running this test manually in your cluster? That will give you an opportunity to see why its failing.

**Comment by mvdan** [comment]
So that's the thing - the integration tests pass on my machine, both before and after that commit.

**Comment by mvdan** [comment]
@vishh with that last commit we should see what the error is without having to go through the logs ourselves.

**Comment by mvdan** [comment]
@vishh okay, so one can now see that the failure is that GCM isn't enabled for the account:

> Access Not Configured. The API (Cloud Monitoring API) is not enabled for your project. Please use the Google Developers Console to update your configuration.

**Comment by mvdan** [comment]
Can't fix it from home, but will do so tomorrow morning.

**Comment by mvdan** [comment]
retest this please

**Comment by mvdan** [comment]
Huzzah!

**Comment by mvdan** [comment]
@vishh cleaned up my commits, jenkins should succeed again in a few minutes. Could you review and merge?

**Comment by mvdan** [comment]
It failed for some weird issue. retest this please

**Comment by vishh** [comment]
LGTM. Waiting for jenkins.

**Comment by vishh** [comment]
Thanks @mvdan

**Pull request merged**
