### PR TITLE
Grafana services and docker image update

### PR DESCRIPTION
**Pull request by simon3z**

### CODE REVIEW

**Comment by simon3z** [comment]
/cc @vishh @jimmidyson 

If we have an agreement on using apache + its reverse proxy I can go ahead and complete that as well.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM. Thanks for the cleanup @simon3z. Will merge once the tests pass.
@simon3z: Lets discuss about apache vs native go server in #183.

**Comment by vishh** [comment]
@simon3z: #183 acheives the same goals as this PR. It includes the reverse proxy changes as well. Can you take a look at that and see if that works for you?

**Comment by vishh** [comment]
@simon3z: I merged #183 yesterday which adds a RP to access Influxdb. Can you see if that works for you?

**Pull request closed without merging**
