### PR TITLE
Update kubernetes deps 

### PR DESCRIPTION
**Pull request by vishh**
I  hope that some of the watch errors will disappear with this update.

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM, waiting on CIs

**Comment by vmarmol** [comment]
Jenkins failed:

```
+ deploy/build-test.sh
~/workspace/project/src/github.com/GoogleCloudPlatform/heapster/deploy ~/workspace/project/src/github.com/GoogleCloudPlatform/heapster
../Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/context.go:22:2: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/auth/user" in any of:
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.3.3/src/pkg/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/user (from $GOROOT)
	/var/lib/jenkins/workspace/project/src/github.com/GoogleCloudPlatform/heapster/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/user (from $GOPATH)
	/var/lib/jenkins/workspace/project/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/user
godep: go exit status 1
```

**Comment by vishh** [comment]
Fixed the build issue. Waiting on e2e to see if there are any additional issues.

**Comment by vmarmol** [comment]
It's still unhappy it seems :(

**Comment by vishh** [comment]
I have spent a lot of time now attempting to restrict godep changes to just the kubernetes package. I hope it works this time around.

**Comment by vishh** [comment]
Ping @vmarmol. This can be merged now.

**Comment by vmarmol** [comment]
Just saw it had gone green :) LGTM

**Pull request merged**
