### PR TITLE
Added new sink for autoscaling purposes.

### PR DESCRIPTION
**Pull request by piosz**
Need more work. Especially documentation update.

@vishh, could you please take a look before your vacation and then reassign to someone else?

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by yoanisgil** [comment]
Travis CI build is not passing.

**Comment by vishh** [comment]
Overall LGTM. @vmarmol should be able to help you out while I am gone @piosz

**Comment by piosz** [comment]
Fixed test. Some minor changes.

**Comment by piosz** [comment]
cc @jszczepkowski

**Comment by vishh** [comment]
@piosz: Can you post a snapshot of the data in GCM? Since we don't have any e2e for this sink yet, manual verification will help.

**Comment by piosz** [comment]
The snapshot is here: http://pastebin.com/uNJjZLNr
I'm not sure if it is what you wanted.

**Comment by vishh** [comment]
Thanks. Lgtm

**Comment by piosz** [comment]
Thanks!

**Pull request merged**
