### PR TITLE
Fix issue with exporting host_id for pod containers.

### LINKED ISSUE #348: host_id label only populated some of the time
In the heapster 0.14.1 HTTP API, only some of the timeseries I'm receiving come with host_id populated, even though hostname is always populated.

In a default kubernetes cluster with no custom pods running, it looks like host_id is populated for the "/system", "/kubelet", "/kube-proxy", and "/docker-daemon", but not for anything else (i.e. "machine" or any actual pods).

### PR DESCRIPTION
**Pull request by vishh**
Fixes #348 

cc @a-robinson @rjnagal

### CODE REVIEW

**Comment by rjnagal** [comment]
What other endpoint do we export host_id at?

**Comment by vishh** [comment]
The monitoring sinks like InfluxDB should have it.

**Comment by vishh** [comment]
Here is a running instance of heapster with this change: http://104.197.27.4:8082/api/v1/metric-export

**Comment by a-robinson** [comment]
I can't hit that endpoint, but LGTM.

**Comment by rjnagal** [comment]
LGTM

**Comment by vishh** [comment]
@a-robinson: Try again.

**Comment by a-robinson** [comment]
Much better, thanks!

**Pull request merged**
