### PR TITLE
External save block

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
This is really weird. I couldn't find a reference to this issue anywhere, so to confirm that indeed reading from an empty buffered channel doesn't block, I set up a play.golang.org example: https://play.golang.org/p/abMIOJa0FJ

And it does indeed block. So this issue seems to come from someplace else.

**Comment by vmarmol** [comment]
LGTM

**Comment by mvdan** [comment]
@vmarmol now it is ready to merge :)

**Comment by vmarmol** [comment]
Thanks :) LGTM

**Pull request merged**
