### PR TITLE
Updating deps

### PR DESCRIPTION
**Pull request by vishh**
This is big PR. I had to do it in one go since godep was mad with cadvisor and kubernetes both including libcontainer.

### CODE REVIEW

**Comment by vishh** [comment]
cc @rjnagal

**Comment by vishh** [comment]
@saad-ali can you review this PR?
Rohit might be busy.

**Comment by vishh** [comment]
Self merging since a release needs to be cut soon.

**Comment by saad-ali** [comment]
Way too many files to look at. But I assume you did some manual testing to verify things are still working. If so, LGTM.

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
