### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by mvdan**
```
% godep go test -v -retries 3 --timeout=5m '--vmodule=*=2'
=== RUN TestHeapster
I0722 17:48:11.240633   22204 heapster_api_test.go:110] built and pushed heapster image
--- PASS: TestHeapster (50.15s)
PASS
ok      github.com/GoogleCloudPlatform/heapster/integration     50.159s
```

Need I say more? :)

### CODE REVIEW

**Comment by mvdan** [comment]
CC @vmarmol @vishh @afein

**Comment by mvdan** [comment]
FWIW, this is passing on a Kubernetes 1.0.1 cluster.

**Comment by mvdan** [comment]
Included #426 into this PR.

**Comment by vishh** [comment]
Thanks for the fix @mvdan. Much appreciated!

**Comment by mvdan** [comment]
Still failed, with the same error that #426 had. Agh!

**Comment by vishh** [comment]
LGTM

**Pull request merged**
