### PR TITLE
InfluxDB is now proxied by Nginx for Grafana seamless integration.

### LINKED ISSUE #135: Proxy calls to InfluxDB with nginx
So, having something like
```
yaml
- name: "INFLUXDB_HOST"
  value: '"+window.location.hostname+"/api/v1beta1/proxy/services/monitoring-influxdb'
```
is very limitative when it comes to running ```influxdb``` + ```grafana```, especially inside Kubernetes.

See [my suggested solution](https://github.com/GoogleCloudPlatform/kubernetes/issues/4841).

### PR DESCRIPTION
**Pull request by pires**
Fixes #135 

Grafana section on ```influx-grafana-controller.yaml``` should be like this now
```
yaml
- name: grafana
    image: kubernetes/heapster_grafana:v0.4
        env: 
            - name: "HTTP_USER"
              value: "admin"
            - name: "HTTP_PASS"
              value: "admin"
```
or something like (these are the default values, by the way)
```yaml
- name: grafana
    image: kubernetes/heapster_grafana:v0.4
        env: 
            - name: "HTTP_USER"
              value: "admin"
            - name: "HTTP_PASS"
              value: "admin"
            - name: "INFLUXDB_PROTO"
              value: "http"
            - name: "INFLUXDB_HOST"
              value: "localhost"
            - name: "INFLUXDB_PORT"
              value: "8086"
```

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by pires** [comment]
@vishh as requested, I've updated the InfluxDB + Grafana replication controller.

**Comment by vishh** [comment]
@pires: This PR needs a rebase.

**Comment by pires** [comment]
@vishh done.

**Comment by vishh** [comment]
@pires: I am not able to access the Grafana bashboard via the proxy on the master - `https://<masterIP>/api/v1beta1/proxy/services/monitoring-grafana/`.
Does this work for you?

**Comment by agios** [comment]
:+1: 
@vishh The url you posted does not work for me either, but the one used in this PR does work
`https://<DBHOST>:<DBPORT>/db/`

**Comment by vishh** [comment]
@agios: Happy to know that the basic PR works for you. The reason for not merging this PR yet is due to the fact that setting up a client facing service in kubernetes is neither simple nor cross-platform compatible. I intend to pick this up and get Grafana to work with both a public ip and via the proxy.
If you have some time feel free to pick this up.

**Comment by Andre-Freitas** [comment]
@agios this works if you replace `influxdb-grafana-controller.yaml` `grafana` image with `pires/grafana`.

**Comment by pires** [comment]
@Andre-Freitas exactly.

**Comment by vishh** [comment]
Closing this PR in favor of #183. The expected functionality is already on HEAD. The next release of the grafana image will have all the changes.

**Pull request closed without merging**
