### PR TITLE
Go generate fixes

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
@vishh `hooks/check_boilerplate.sh` complains about the generated file not having the copyright. It's a generated file, so I'm thinking we should make the script ignore that file. Thoughts?

**Comment by mvdan** [comment]
As said above, made `hooks/check_boilerplate.sh` ignore go generated files, which is only `*extpoints/extpoints.go` for now.

**Comment by vishh** [comment]
Excluding generated files SGTM. Why not delete and regenerate extpoints? With this PR will extpoints.go be regerated whenever that package is modified?

**Comment by mvdan** [comment]
See my commit messages - `go generate` is not supposed to be run by the user, but by the developer(s).

When what package is modified, `go-extpoints` or `heapster`? At the moment, neither. It is up to whomever changes the `go-extpoints` input to re-run the tool. And if the tool ever changes, which it shouldn't do often, someone would eventually run the updated tool and notice.

I thought about making travis run `go generate` and check if it is up to date. I could bundle that with a `go-extpoints` in `Godep/` so that it never breaks in the future. What do you think?

Side note: master currently has this problem. If `go-extpoints` breaks, heapster breaks, because we just `go get` it via master.

**Comment by vishh** [comment]
I meant chnages to heapster extpoints/interface.go which should result in
regenerating extpoints/ expoints.go. Vendoring go-extpoints makes sense.

**Comment by mvdan** [comment]
I'll vendor `go-extpoints` and add the thing to travis.

**Comment by mvdan** [comment]
retest this please

**Comment by mvdan** [comment]
retest this please

**Comment by mvdan** [comment]
@vishh any idea why jenkins failed twice with the same error message?

**Comment by mvdan** [comment]
Otherwise this is ready to be merged

**Comment by vishh** [comment]
retest this please

**Comment by mvdan** [comment]
The new jenkins build failed, but an earlier one succeeded. Jenkins is not being very deterministic.

**Comment by vishh** [comment]
retest this please

**Comment by mvdan** [comment]
green again!

**Pull request merged**
