### PR TITLE
Fetch stats in parallel.

### PR DESCRIPTION
**Pull request by vishh**
This PR also includes some simple refactoring of code. Tested manually.

### CODE REVIEW

**Comment by rjnagal** [comment]
Is the integration expected to fail?
The changes look good otherwise

**Comment by vishh** [comment]
No. Restarted the build.

**Comment by vishh** [comment]
@vmarmol: Addressed comments and fixed some more bugs. PTAL

**Comment by vmarmol** [comment]
I think we can merge the last two commits. Outside of the types question, LGTM

**Comment by vishh** [comment]
@vmarmol: made changes as per your comment. Will merge once the build is green.

**Comment by rjnagal** [comment]
LGTM

**Pull request merged**
