### PR TITLE
Add missing gofuzz deps

### PR DESCRIPTION
**Pull request by vishh**
Looks like I had update Godeps.json but failed to add the actual dependencies.

cc @vmarmol

### CODE REVIEW

**Comment by rjnagal** [comment]
Is the failure expected:
github.com/GoogleCloudPlatform/heapster/sinks/api
sinks/api/decoder_test.go:32: cannot use struct {} literal (type struct {}) as type api.AggregateData in argument to NewDecoder().Timeseries

**Comment by vmarmol** [comment]
Hehehehe :D

**Comment by vishh** [comment]
The test failure is real. Fixed the issue.

**Comment by vishh** [comment]
I am not sure why jenkins did not update the PR, but the test did pass: http://104.154.52.74/job/heapster-e2e-gce/573/

**Comment by rjnagal** [comment]
LGTM

Merging

**Pull request merged**
